---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privilegedBuild
  namespace: {{ include "tekton-app.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privilegedBuild
subjects:
- kind: ServiceAccount
  name: build-bot
  namespace: {{ include "tekton-app.fullname" . }}
