apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: buildah-blog
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: image-build
spec:
  description: >-
    Buildah task builds source into a container image and
    then pushes it to a container registry.

    Buildah Task builds source into a container image using Project Atomic's
    Buildah build tool.It uses Buildah's support for building from Dockerfiles,
    using its buildah bud command.This command executes the directives in the
    Dockerfile to assemble a container image, then pushes that image to a
    container registry

  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image.
      default: quay.io/buildah/stable:v1.15.1
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay  
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the directory to use as context.
      default: .
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "false"
    - name: FORMAT
      description: OCS format or docker?
      type: string
      default: "docker"
    - name: BUILD_EXTRA_ARGS
      description: Extra parameters passed for the build command when building images.
      default: ""
    - name: PUSH_EXTRA_ARGS
      description: Extra parameters passed for the push command when pushing images.
      type: string
      default: ""      
  workspaces:
  - name: source

  steps:
  - script: |
      # Buildah steps for git hash and build the image with git hash tag
      #
      cat .git/FETCH_HEAD
      GIT_HASH=$(head -1 .git/FETCH_HEAD |awk '{print $1}')
      echo "Git hash $GIT_HASH"
      buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
        $(params.BUILD_EXTRA_ARGS) --format=$(params.FORMAT) \
        --tls-verify=$(params.TLSVERIFY) --no-cache \
        -f $(params.DOCKERFILE) -t $(params.IMAGE):$GIT_HASH $(params.CONTEXT)
    image: $(params.BUILDER_IMAGE)
    name: build
    workingDir: $(workspaces.source.path)
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers

  - script: |
      # Buildah push
      # 
      cat .git/FETCH_HEAD
      GIT_HASH=$(head -1 .git/FETCH_HEAD |awk '{print $1}')
      echo "Git hash $GIT_HASH"  
      #
      #
      buildah --storage-driver=$(params.STORAGE_DRIVER) push \
        $(params.PUSH_EXTRA_ARGS) --tls-verify=$(params.TLSVERIFY) \
        --digestfile $(workspaces.source.path)/image-digest $(params.IMAGE):$GIT_HASH \
        docker://$(params.IMAGE):$GIT_HASH
    image: $(params.BUILDER_IMAGE)
    name: push
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: $(workspaces.source.path)

  - name: digest-to-results
    image: $(params.BUILDER_IMAGE)
    script: cat $(workspaces.source.path)/image-digest | tee /tekton/results/IMAGE_DIGEST
        
  volumes:
  - emptyDir: {}
    name: varlibcontainers
