apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.helmName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.helmSize }}
