---
# Example Application repo
app:
  gitUrl: https://github.com/NissesSenap/openliberty-app.git
  gitRevision: main

# artifactory global settings
artifactory:
  url: 'artifactory.example.com'
  image: 'external-app'
  repo: 'docker-app1'
  token: super-secret-token
  username: user1

# pvc global settings
# In the future we will need to use PVCTemplate but this feature currently isn't implemented in the tekton release that we are using.
pvc:
  size: 1Gi
  helmSize: 1Gi
  name: 'app-pvc'
  helmName: 'app-helm-pvc'

# Argo Git global settings
argo:
  gitUrl: 'https://github.com/NissesSenap/tekton-play.git'

fullnameOverride: "app-ci"

helm:
  chartsDir: 'app'
  releaseName: 'app'
  overwriteValues: "image.repository=image-registry.openshift-image-registry.svc:5000/app-ci/app,image.tag=latest"

integration:
  hostname: 'app'
  contextRoot: 'app'
